"""add_filing_fields

Revision ID: 7c2724988446
Revises: e290f1d5306d
Create Date: 2026-06-17 13:53:47.181289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c2724988446'
down_revision: Union[str, Sequence[str], None] = 'e290f1d5306d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'opening_balance',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('invoices', 'source',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'source',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('businesses', 'opening_balance',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    # ### end Alembic commands ###
